/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Meu_segundo_projeto_Java;

//HErança 
//Poliformismo
public class App {

    

    public static void main(String[] args) {
    	Equipe equipeKartAzul = new Equipe ();
    	Equipe equipeKartVermelho= new Equipe ();
    	equipeKartVermelho.v1 = new Veiculo (new MotordeKartVermelho());
    	equipeKartVermelho.v2 = new Veiculo(new MotordeKartVermelho());
    	equipeKartVermelho.p1 = new Piloto ("Sergio", 30);
    	equipeKartVermelho.p2 = new Piloto("Kleber",30);
    	equipeKartVermelho.mecanicos.add(new Mecanico());
    	equipeKartVermelho.mecanicos.add(new Mecanico());
    	equipeKartVermelho.mecanicos.add(new Mecanico());
    	equipeKartVermelho.mecanicos.add(new Mecanico());
    	equipeKartVermelho.mecanicos.add(new Mecanico());
    	
    	equipeKartVermelho.v1.Acelerar(4);
    	System.out.println(equipeKartVermelho.v1.Acelerar(5));
    
    	
    }
 
}
